version: '3.7'

services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: realize start --run
    ports:
      - 9998:9998
      - 23450:23450
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - grpc-training
networks:
  grpc-training:
    name: grpc-training
