version: '3.7'

services:
  grpc-server:
    build:
      context: .
      dockerfile: build/package/docker/grpc/Dockerfile
      target: build
    volumes:
      - ./:/go/app
    command: air
    ports:
      - 9998:9998
      - 23450:23450
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    networks:
      - grpc-training
  grpc-gateway:
    build:
      context: .
      dockerfile: build/package/docker/gateway/Dockerfile
      target: build
    command: go run ./cmd/gateway/main.go
    environment:
      DEPLOY_STAGE: local
    ports:
      - 8081:8081
    networks:
      - grpc-training
networks:
  grpc-training:
    name: grpc-training
