// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/cat.proto

package cat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindCuteCatMessage struct {
	CatId                string   `protobuf:"bytes,1,opt,name=catId,proto3" json:"catId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindCuteCatMessage) Reset()         { *m = FindCuteCatMessage{} }
func (m *FindCuteCatMessage) String() string { return proto.CompactTextString(m) }
func (*FindCuteCatMessage) ProtoMessage()    {}
func (*FindCuteCatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_373801c440db0e38, []int{0}
}

func (m *FindCuteCatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindCuteCatMessage.Unmarshal(m, b)
}
func (m *FindCuteCatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindCuteCatMessage.Marshal(b, m, deterministic)
}
func (m *FindCuteCatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindCuteCatMessage.Merge(m, src)
}
func (m *FindCuteCatMessage) XXX_Size() int {
	return xxx_messageInfo_FindCuteCatMessage.Size(m)
}
func (m *FindCuteCatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FindCuteCatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FindCuteCatMessage proto.InternalMessageInfo

func (m *FindCuteCatMessage) GetCatId() string {
	if m != nil {
		return m.CatId
	}
	return ""
}

type CuteCatResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CuteCatResponse) Reset()         { *m = CuteCatResponse{} }
func (m *CuteCatResponse) String() string { return proto.CompactTextString(m) }
func (*CuteCatResponse) ProtoMessage()    {}
func (*CuteCatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_373801c440db0e38, []int{1}
}

func (m *CuteCatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CuteCatResponse.Unmarshal(m, b)
}
func (m *CuteCatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CuteCatResponse.Marshal(b, m, deterministic)
}
func (m *CuteCatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CuteCatResponse.Merge(m, src)
}
func (m *CuteCatResponse) XXX_Size() int {
	return xxx_messageInfo_CuteCatResponse.Size(m)
}
func (m *CuteCatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CuteCatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CuteCatResponse proto.InternalMessageInfo

func (m *CuteCatResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CuteCatResponse) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*FindCuteCatMessage)(nil), "FindCuteCatMessage")
	proto.RegisterType((*CuteCatResponse)(nil), "CuteCatResponse")
}

func init() { proto.RegisterFile("pb/cat.proto", fileDescriptor_373801c440db0e38) }

var fileDescriptor_373801c440db0e38 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0xd2, 0x4f,
	0x4e, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe2, 0x12, 0x72, 0xcb, 0xcc, 0x4b,
	0x71, 0x2e, 0x2d, 0x49, 0x75, 0x4e, 0x2c, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12,
	0xe1, 0x62, 0x4d, 0x4e, 0x2c, 0xf1, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70,
	0x94, 0x2c, 0xb9, 0xf8, 0xa1, 0xea, 0x82, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0xa1, 0xea, 0xc0, 0x6c, 0x90, 0x58, 0x76, 0x66, 0x5e, 0x8a,
	0x04, 0x13, 0x44, 0x0c, 0xc4, 0x36, 0xb2, 0xe5, 0x62, 0x76, 0x4e, 0x2c, 0x11, 0x32, 0xe3, 0xe2,
	0x46, 0xb2, 0x4d, 0x48, 0x58, 0x0f, 0xd3, 0x6e, 0x29, 0x01, 0x3d, 0x34, 0x4b, 0x94, 0x18, 0x92,
	0xd8, 0xc0, 0x8e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x46, 0xb1, 0xe0, 0xbc, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CatClient is the client API for Cat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CatClient interface {
	FindCuteCat(ctx context.Context, in *FindCuteCatMessage, opts ...grpc.CallOption) (*CuteCatResponse, error)
}

type catClient struct {
	cc *grpc.ClientConn
}

func NewCatClient(cc *grpc.ClientConn) CatClient {
	return &catClient{cc}
}

func (c *catClient) FindCuteCat(ctx context.Context, in *FindCuteCatMessage, opts ...grpc.CallOption) (*CuteCatResponse, error) {
	out := new(CuteCatResponse)
	err := c.cc.Invoke(ctx, "/Cat/FindCuteCat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatServer is the server API for Cat service.
type CatServer interface {
	FindCuteCat(context.Context, *FindCuteCatMessage) (*CuteCatResponse, error)
}

// UnimplementedCatServer can be embedded to have forward compatible implementations.
type UnimplementedCatServer struct {
}

func (*UnimplementedCatServer) FindCuteCat(ctx context.Context, req *FindCuteCatMessage) (*CuteCatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindCuteCat not implemented")
}

func RegisterCatServer(s *grpc.Server, srv CatServer) {
	s.RegisterService(&_Cat_serviceDesc, srv)
}

func _Cat_FindCuteCat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindCuteCatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatServer).FindCuteCat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cat/FindCuteCat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatServer).FindCuteCat(ctx, req.(*FindCuteCatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cat",
	HandlerType: (*CatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindCuteCat",
			Handler:    _Cat_FindCuteCat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/cat.proto",
}
